### ISSUE TITLE
Tag Request

### ISSUE THREAD

**Issue by theshadowake** [ExcessiveAmountsOfZombies/ServerBrowser#1]
Please could you add a tag AwakeningMedievalMasonry

Thanks.

**Comment by oliviajumba** [comment]
Please also add:

- ATM 8
- Direwolf20 1.19
- OccultCraft
- FTB Plexiglass Mountain
- ATMG
- CraftDownUnder
- StoneBlock 3
- Vault Hunters 3rd Edition
- Strictly Medieval 2
- Engineer's Life 2
- World of Dragons - A New Age
- Techopolis
- R.A.D 2
- Enigmatica 6: Expert
- Ragnamod VI
- Dungeons, Dragons & Space Shuttles
- Divine Journey 2
- Sky Factory 4
- Inclusive
- ATM 7
- ATM 7 - To The Sky
- FTB Inferno
- Create: Astral
- Ragnamod VI -  In the Sky
- RLCraft

**Comment by ExcessiveAmountsOfZombies** [comment]
added all except the CraftDownUnder pack, since that's made for a specific community, i'd use the "official servers" support that is explained on the mods page.

if it gets to a point where people are making community servers off of your official server pack it could be revisited, but I don't think that'll be likely...
